### PR TITLE
Transfer code ownership of FairMQ.SDK and FairMQ DDS plugin to ODC

### PR DESCRIPTION
**Pull request by dennisklein**
Developing the former `fair::mq::sdk::Topology` (now proposed `odc::core::Topology`) class and the former FairMQ `dds` plugin (now proposed `odc` Plugin) within the ODC repository allows a much cheaper evolution of these components (which are naturally tightly integrated with ODC) and enables a simplified dependency tree: [see slides for illustration](https://docs.google.com/presentation/d/1U5HtDdHOESY7GQ0Jxm3MSNnOPjGZjG-XhxjjhaCLh0M/edit?usp=sharing).

This PR ports
* all usages of FairLogger to ODC's native Logger,
* some of the names to ODC's naming conventions (there is still some renaming missing, let me know, if you need this done before an initial merge and also what you want to be changed!),
* all unit tests from Googletest to ODC's choice Boost.UTF

Since the PR adds quite a hefty number of lines of code, I recommend reviewing it by commit which should resemble smaller coherent changeset with additional description in the commit messages.

### CODE REVIEW

**Comment by dennisklein** [comment]
The test suite runs kinda ok for me (with the usual occasional failing test):

```console
❯ cmake --build build --target test
[0/1] Re-running CMake...
-- Building ODC 0.28.8.gc91fbd6 ...
-- Using protobuf 3.14.0
-- Using gRPC
-- Using DDS 3.5.14
-- Found Boost: /usr/include (found suitable version "1.75.0", minimum required is "1.67") found components: log log_setup thread program_options filesystem system regex unit_test_framework date_time chrono atomic
-- Using FairLogger 1.9.3
-- Looking for FairLogger dependencies: fmt
-- Using FairMQ 1.4.38-58-g0a7b0238
-- Looking for FairMQ dependencies: Boost;FairLogger;Threads;asio;fmt
-- Found Boost: /usr/include (found suitable version "1.75.0", minimum required is "1.67") found components: container program_options filesystem date_time regex system log log_setup thread chrono atomic
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dklein/projects/ODC/build
[0/1] Running tests...
Test project /home/dklein/projects/ODC/build
      Start  1: odc-cli-server::default
 1/33 Test  #1: odc-cli-server::default .....................................................   Passed   22.84 sec
      Start  2: odc-cli-server::test_1
 2/33 Test  #2: odc-cli-server::test_1 ......................................................   Passed    1.21 sec
      Start  3: odc_core_lib::async_op/cancel
 3/33 Test  #3: odc_core_lib::async_op/cancel ...............................................   Passed    0.02 sec
      Start  4: odc_core_lib::async_op/complete
 4/33 Test  #4: odc_core_lib::async_op/complete .............................................   Passed    0.02 sec
      Start  5: odc_core_lib::async_op/construction_with_handler
 5/33 Test  #5: odc_core_lib::async_op/construction_with_handler ............................   Passed    0.02 sec
      Start  6: odc_core_lib::async_op/default_construction
 6/33 Test  #6: odc_core_lib::async_op/default_construction .................................   Passed    0.02 sec
      Start  7: odc_core_lib::async_op/timeout
 7/33 Test  #7: odc_core_lib::async_op/timeout ..............................................   Passed    0.07 sec
      Start  8: odc_core_lib::async_op/timeout2
 8/33 Test  #8: odc_core_lib::async_op/timeout2 .............................................   Passed    0.02 sec
      Start  9: odc_core_lib::multiple_topologies/change_state_full_lifecycle_interleaved
 9/33 Test  #9: odc_core_lib::multiple_topologies/change_state_full_lifecycle_interleaved ...   Passed    5.52 sec
      Start 10: odc_core_lib::multiple_topologies/change_state_full_lifecycle_serial
10/33 Test #10: odc_core_lib::multiple_topologies/change_state_full_lifecycle_serial ........   Passed    5.76 sec
      Start 11: odc_core_lib::topology/aggregated_topology_state_comparison
11/33 Test #11: odc_core_lib::topology/aggregated_topology_state_comparison .................   Passed    0.02 sec
      Start 12: odc_core_lib::topology/async_change_state
12/33 Test #12: odc_core_lib::topology/async_change_state ...................................   Passed    1.67 sec
      Start 13: odc_core_lib::topology/async_change_state_collection_view
13/33 Test #13: odc_core_lib::topology/async_change_state_collection_view ...................   Passed    1.54 sec
      Start 14: odc_core_lib::topology/async_change_state_concurrent
14/33 Test #14: odc_core_lib::topology/async_change_state_concurrent ........................   Passed    1.53 sec
      Start 15: odc_core_lib::topology/async_change_state_future
15/33 Test #15: odc_core_lib::topology/async_change_state_future ............................   Passed    1.58 sec
      Start 16: odc_core_lib::topology/async_change_state_timeout
16/33 Test #16: odc_core_lib::topology/async_change_state_timeout ...........................   Passed    1.59 sec
      Start 17: odc_core_lib::topology/async_change_state_with_executor
17/33 Test #17: odc_core_lib::topology/async_change_state_with_executor .....................   Passed    1.57 sec
      Start 18: odc_core_lib::topology/async_set_properties_concurrent
18/33 Test #18: odc_core_lib::topology/async_set_properties_concurrent ......................   Passed    1.72 sec
      Start 19: odc_core_lib::topology/async_set_properties_timeout
19/33 Test #19: odc_core_lib::topology/async_set_properties_timeout .........................   Passed    1.67 sec
      Start 20: odc_core_lib::topology/change_state
20/33 Test #20: odc_core_lib::topology/change_state .........................................   Passed    1.59 sec
      Start 21: odc_core_lib::topology/change_state_full_device_lifecycle
21/33 Test #21: odc_core_lib::topology/change_state_full_device_lifecycle ...................   Passed    2.01 sec
      Start 22: odc_core_lib::topology/change_state_full_device_lifecycle2
22/33 Test #22: odc_core_lib::topology/change_state_full_device_lifecycle2 ..................   Passed    6.39 sec
      Start 23: odc_core_lib::topology/construction
23/33 Test #23: odc_core_lib::topology/construction .........................................   Passed    1.40 sec
      Start 24: odc_core_lib::topology/construction2
24/33 Test #24: odc_core_lib::topology/construction2 ........................................   Passed    1.47 sec
      Start 25: odc_core_lib::topology/get_properties
25/33 Test #25: odc_core_lib::topology/get_properties .......................................   Passed    1.75 sec
      Start 26: odc_core_lib::topology/mixed_state
26/33 Test #26: odc_core_lib::topology/mixed_state ..........................................   Passed    1.61 sec
      Start 27: odc_core_lib::topology/set_and_get_properties
27/33 Test #27: odc_core_lib::topology/set_and_get_properties ...............................   Passed    1.67 sec
      Start 28: odc_core_lib::topology/set_properties
28/33 Test #28: odc_core_lib::topology/set_properties .......................................   Passed    1.67 sec
      Start 29: odc_core_lib::topology/set_properties_mixed
29/33 Test #29: odc_core_lib::topology/set_properties_mixed .................................   Passed    1.68 sec
      Start 30: odc_core_lib::topology/wait_for_state_full_device_lifecycle
30/33 Test #30: odc_core_lib::topology/wait_for_state_full_device_lifecycle .................   Passed    1.92 sec
      Start 31: odc_custom_commands::format/construction
31/33 Test #31: odc_custom_commands::format/construction ....................................   Passed    0.01 sec
      Start 32: odc_custom_commands::format/serialization_binary
32/33 Test #32: odc_custom_commands::format/serialization_binary ............................   Passed    0.01 sec
      Start 33: odc_custom_commands::format/serialization_json
33/33 Test #33: odc_custom_commands::format/serialization_json ..............................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 33

Total Test time (real) =  71.59 sec

```

Not sure what's the problem on the CI macs, I leave it to you to install a working CI environment ...

**Comment by dennisklein** [comment]
address sanitizer errors already reported: FairRootGroup/DDS#373

**Comment by AndreyLebedev** [comment]
@dennisklein Thanks, I started checking the PR.

On macOS
`export DYLD_LIBRARY_PATH=@CMAKE_INSTALL_PREFIX@/@PROJECT_INSTALL_LIBDIR@:$DYLD_LIBRARY_PATH`
is needed for `ex-env.sh.in`.

Tests are working for me.

**Comment by AndreyLebedev** [comment]
1) I would also move `custom-commands` sources to `plugins/fairmq/odc` and rename it to, for example, `fairmq-plugin-commands` or just `plugin-commands`. Probably you have a better name suggestion. `custom-commands` sounds too general to me.
2) For a longer-term perspective we should use `protobuf` instead of `flatbuffers`. Since `protobuf` is already used by `ODC`.

**Comment by dennisklein** [comment]
>     1. I would also move `custom-commands` sources to `plugins/fairmq-odc` and rename it to, for example, `fairmq-plugin-commands` or just `plugin-commands`. Probably you have a better name suggestion. `custom-commands` sounds too general to me.

ok, what about this:
| | **directory** | **target** | **C++ namespace** |
| --- | --- | --- | --- |
| old | `/custom-commands` | `odc_custom_commands` | `odc::cc` |
| new | `/plugins/fairmq-odc/commands` | `odc_plugins_fairmq_commands` | `odc::plugins::cc`? (`FairMQPlugin_odc` is currently in namespace `odc::plugins`) |

There are two dependees on `odc_plugins_fairmq_commands`:

https://github.com/FairRootGroup/ODC/pull/18/files#diff-066fc92ea5c360d7929dc302584747739c68999bfa433b8a3657b4467d6a8413R10-R20

and

https://github.com/FairRootGroup/ODC/pull/18/files#diff-8f52846645b80806e11fbe318820659ca6d81d2fe305d815bb97f62d2102e1fdR41-R48

**Comment by AndreyLebedev** [comment]
@dennisklein ok, looks good

**Comment by AndreyLebedev** [comment]
Do you plan to leave `dds` plugin in the `FairMQ`? 
For the moment people in ALICE use `dds` plugin and we basically have to smoothly transition everybody to `odc`. I guess it can be done relatively easy for the moment because there are not so many workflows.

**Comment by dennisklein** [comment]
> Do you plan to leave `dds` plugin in the `FairMQ`?
> For the moment people in ALICE use `dds` plugin and we basically have to smoothly transition everybody to `odc`. I guess it can be done relatively easy for the moment because there are not so many workflows.

Yes, nothing will be deleted from FairMQ right now. Eventually, `dds` plugin would go away, but not very soon.

Regarding the transition, IMHO, they should not hard-code the plugin anywhere. The `-P dds|odc` flag should be added by e.g. the DPL xml exporter - then it would be trivial to choose a different plugin.

**Comment by AndreyLebedev** [comment]
@dennisklein I looked through the code. Looks good to me. 

1) As you mentioned some of the names to ODC's naming conventions are not implemented. But this we can skip for the initial commit.
2) Code formatting. We use `clang-format version 12.0.0`. To format the code - `make format-code`.

**Comment by AndreyLebedev** [comment]
@dennisklein I moved `custom-commands` and `fairmq-plugin` to `fairmq`. 
Also, I've formatted the code.
Your `master` branch is updated.
Still thinking if it makes sense to create a separate library for `fairmq` related stuff.

**Comment by dennisklein** [comment]
> @dennisklein I moved `custom-commands` and `fairmq-plugin` to `fairmq`.
> Also, I've formatted the code.
> Your `master` branch is updated.

Oh thx, haven't gotten to it yet.

> Still thinking if it makes sense to create a separate library for `fairmq` related stuff.

Ya, however you like. Also you may consider making it a CMake OBJECT library. That would not create a separate shared object, but only makes the structure within CMake more fine-grained.

**Comment by dennisklein** [comment]
Ok, now I lost track, what else needs to be done?

(The `All checks` status check which says `In progress` indefinitely should go away on the next PR)

**Comment by AndreyLebedev** [comment]
> Ok, now I lost track, what else needs to be done?
> 
> (The `All checks` status check which says `In progress` indefinitely should go away on the next PR)

So basically it works now. 
The only thing missing is moving the `Topology` related code to a `fairmq` directory (and optionally to a separate library). 
I'll do it probably today.
And then will merge the code.

**Review by AndreyLebedev — APPROVED** [review]

**Pull request merged**
