### PR TITLE
Set InfoLogger message levels (same translation as in O2)

### PR DESCRIPTION
**Pull request by davidrohr**
couldn't test on the EPN since for some reason ODC doesn't compile as development package.
But the patch is trivial enough that I think I didn't break anything.

### CODE REVIEW

**Comment by rbx** [comment]
I don't have a test in ODC that uses InfoLogger to confirm that this is OK. But indeed, it looks trivial enough.

Had to look up what the magic numbers mean. I'll leave it here for future reference:

> Level: the relative visibility of the message and associated target audience to whom is addressed the message: from 1 (important, visible to all) to 99 (low-level debug message, for experts only). The following ranges are defined to categorize messages for a typical production environment: operations (1-5) support (6-10) developer (11-20) trace (21-99).

(from https://github.com/AliceO2Group/InfoLogger/blob/master/doc/README.md#api-for-developers)

**Comment by davidrohr** [comment]
@rbx : thx, could we have a new tag with this in?

**Comment by rbx** [comment]
I was planning to make one end of this week. But if you want I can tag this already as is and make one more later.

**Comment by davidrohr** [comment]
> I am planning to make one end of this week. But if you want I can tag this already as is and make one more later.

End of this week should be fine. I think in any case we would probably be quite late for the current update.

**Pull request merged**
